server.port=8082

spring.datasource.url=jdbc:h2:mem:postsdb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://dev-gkz812m34rwi0rbp.us.auth0.com/.well-known/jwks.json
auth0.audience=https://twtr-api

# URL del User Service
user.service.url=http://localhost:8081