spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.hvjdhrlylwmosdlpvyvq
spring.datasource.password=Erenylevi0386
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://dev-gkz812m34rwi0rbp.us.auth0.com/.well-known/jwks.json
auth0.audience=https://twtr-api