# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Console (for development)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Server Configuration
server.port=8080


spring.datasource.driver-class-name=org.h2.Driver

# Reemplaza YOUR-DOMAIN con tu dominio de Auth0 (ej: dev-abc123.us.auth0.com)
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://dev-gkz812m34rwi0rbp.us.auth0.com/.well-known/jwks.json

# Audience que definiste en Auth0 ? APIs
auth0.audience=https://twtr-api